"""Export decompiled functions to .c files as a zip archive."""

import io
import os
import re
import zipfile
import logging

from .helpers import get_cached_pseudocode
from ..models.database import read_db

log = logging.getLogger(__name__)


def export_to_c_files(sess, selected_functions=None):
    """Export decompiled functions as .c files in a zip archive.

    If selected_functions is provided, only those functions are exported.
    Groups functions by source file if symbol info is available,
    otherwise creates a single file per function group.

    Returns a BytesIO object containing the zip.
    """
    if not sess.db_path:
        raise RuntimeError("No analysis database available")

    db = read_db(sess.db_path)
    functions = db.get("functions", [])
    binary_info = db.get("binary_info", {})
    binary_name = binary_info.get("filename", "binary")
    base_name = os.path.splitext(binary_name)[0]

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        header = (
            f"/* Decompiled from: {binary_name}\n"
            f" * Architecture: {binary_info.get('arch', 'unknown')}\n"
            f" * Base address: {binary_info.get('base_addr', 'unknown')}\n"
            f" * Generated by OBAI Reverse Engineering Platform\n"
            f" */\n\n"
        )

        imports_code = _generate_imports_header(db)
        typedefs_code = _generate_typedefs()

        selected_set = set(selected_functions) if selected_functions else None

        grouped = {}
        for func in functions:
            if func.get("is_import"):
                continue

            name = func["name"]
            if selected_set and name not in selected_set:
                continue

            code = get_cached_pseudocode(sess, db, name)
            if not code or code.startswith("//"):
                continue

            source_file = _guess_source_file(name, code)
            grouped.setdefault(source_file, []).append((name, code))

        if not grouped:
            grouped["main"] = []
            for func in functions:
                if func.get("is_import"):
                    continue
                name = func["name"]
                if selected_set and name not in selected_set:
                    continue
                code = db.get("pseudocode_cache", {}).get(name, "")
                if code and not code.startswith("//"):
                    grouped["main"].append((name, code))

        for source_file, funcs in sorted(grouped.items()):
            if not funcs:
                continue

            content = header
            content += imports_code + "\n"
            content += typedefs_code + "\n"

            for func_name, code in funcs:
                content += f"/* Function: {func_name} */\n"
                content += code.strip() + "\n\n"

            filename = f"{base_name}/{source_file}.c"
            zf.writestr(filename, content)

        exports = db.get("exports", [])
        if exports:
            exports_content = header
            exports_content += "/* Exported Functions */\n\n"
            for exp in exports:
                exports_content += f"// {exp['name']} at {exp['address_hex']}\n"
            zf.writestr(f"{base_name}/exports.txt", exports_content)

        imports = db.get("imports", [])
        if imports:
            imports_content = header
            imports_content += "/* Imported Functions */\n\n"
            by_lib = {}
            for imp in imports:
                by_lib.setdefault(imp.get("library", "unknown"), []).append(imp["name"])
            for lib, names in sorted(by_lib.items()):
                imports_content += f"// {lib}\n"
                for n in sorted(names):
                    imports_content += f"//   {n}\n"
                imports_content += "\n"
            zf.writestr(f"{base_name}/imports.txt", imports_content)

    buf.seek(0)
    return buf, f"{base_name}_decompiled.zip"


def _guess_source_file(func_name, code):
    """Try to determine a source file grouping for a function."""
    prefixes = re.findall(r"^([A-Z][a-z]+(?:[A-Z][a-z]+)?)", func_name)
    if prefixes:
        return prefixes[0].lower()

    if func_name.startswith("FUN_") or func_name.startswith("sub_"):
        return "unnamed_functions"

    return "functions"


def _generate_imports_header(db):
    """Generate typical C includes based on the imports seen."""
    imports = db.get("imports", [])
    libs = {imp.get("library", "").lower() for imp in imports}

    lines = []
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")

    if any("kernel32" in l for l in libs):
        lines.append("#include <windows.h>")
    if any("ws2_32" in l for l in libs):
        lines.append("#include <winsock2.h>")
    if any("ntdll" in l for l in libs):
        lines.append("#include <winternl.h>")

    return "\n".join(lines) + "\n"


def _generate_typedefs():
    """Generate common typedefs for decompiled code."""
    return (
        "typedef unsigned char BYTE;\n"
        "typedef unsigned short WORD;\n"
        "typedef unsigned int DWORD;\n"
        "typedef unsigned long long QWORD;\n"
        "typedef int BOOL;\n"
        "typedef void *PVOID;\n"
        "typedef long NTSTATUS;\n"
        "typedef unsigned long ULONG;\n"
        "\n"
    )
